name = "New-mods"
author = "Silverdev2482"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8e4483b5a6b2a0fafe8b9411947c2308bd5e528eebb796f231834392b702367"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
