name = "New-mods"
author = "Silverdev2482"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8750ba63ca5173684285605300810f0673fffb18eeabb15f5f59646d95002cb6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
