name = "New-mods"
author = "Silverdev2482"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "291d6e9efe3479233efbe56b2b69e5ffb9ae3325b996287249b9927d32db34c1"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
